# Generated by Django 4.2.25 on 2025-10-23 12:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('generated_data', models.JSONField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_breakdown', models.JSONField()),
                ('weather_data', models.JSONField(blank=True, default=dict)),
                ('destination_info', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_feedback', models.TextField(blank=True)),
                ('times_viewed', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('rating', 'Rating'), ('modification', 'Modification Request'), ('regeneration', 'Regeneration Request'), ('comment', 'General Comment')], max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('modification_details', models.JSONField(blank=True, default=dict)),
                ('was_addressed', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='trips.itinerary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('travel_style', models.CharField(choices=[('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('cultural', 'Cultural'), ('food_tour', 'Food Tour'), ('family', 'Family-Friendly'), ('romantic', 'Romantic'), ('budget', 'Budget Travel'), ('luxury', 'Luxury')], max_length=20)),
                ('group_size', models.CharField(choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family (3-5)'), ('group', 'Group (6+)')], max_length=20)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('accessibility_needs', models.TextField(blank=True)),
                ('accommodation_preference', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('food', 'Local Food'), ('culture', 'Cultural Experience'), ('adventure', 'Adventure'), ('nightlife', 'Nightlife'), ('shopping', 'Shopping'), ('nature', 'Nature'), ('hidden_gem', 'Hidden Gem')], max_length=20)),
                ('description', models.TextField()),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('best_time', models.CharField(blank=True, max_length=100)),
                ('insider_tip', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=1)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_experiences', to='trips.itinerary')),
            ],
            options={
                'ordering': ['-priority', 'category'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trips.triprequest'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('time_slot', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('food', 'Food & Dining'), ('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('cultural', 'Cultural'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('transport', 'Transportation')], max_length=20)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('booking_required', models.BooleanField(default=False)),
                ('booking_url', models.URLField(blank=True)),
                ('tips', models.TextField(blank=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.itinerary')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['day_number', 'order', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='triprequest',
            index=models.Index(fields=['user', '-created_at'], name='trips_tripr_user_id_6b68dd_idx'),
        ),
        migrations.AddIndex(
            model_name='triprequest',
            index=models.Index(fields=['status'], name='trips_tripr_status_d09bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['trip_request', '-version'], name='trips_itine_trip_re_ff253b_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['itinerary', 'day_number'], name='trips_activ_itinera_448fd5_idx'),
        ),
    ]
