# Generated by Django 4.2.25 on 2025-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
