# Generated by Django 4.2.25 on 2025-11-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_triprequest_deleted_at_triprequest_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='is_deleted',
        ),
    ]
