# Generated by Django 4.2.25 on 2025-12-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_triprequest_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='weather_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time weather was updated', null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='destination_info',
            field=models.JSONField(blank=True, default=dict, help_text='Destination details'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='weather_data',
            field=models.JSONField(blank=True, default=dict, help_text='Weather forecast data'),
        ),
    ]
