# Generated by Django 4.2.25 on 2025-12-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_itinerary_weather_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='destination_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='weather_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='weather_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
